import { UsersStructure } from "../types";

const users: UsersStructure = [
  {
    id: 1,
    username: "johnsmith",
    token: "abc123xyz456",
    email: "johnsmith@example.com",
    isLogged: true,
    shippingDetails: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    username: "janesmith",
    token: "def456hij789",
    email: "janesmith@example.com",
    isLogged: false,
    shippingDetails: "456 Oak St, Anytown, USA",
  },
  {
    id: 3,
    username: "bobdylan",
    token: "klm123nop456",
    email: "bobdylan@example.com",
    isLogged: true,
    shippingDetails: "789 Elm St, Anytown, USA",
  },
  {
    id: 4,
    username: "alicewonderland",
    token: "qrs789tuv012",
    email: "alice@example.com",
    isLogged: false,
    shippingDetails: "111 Maple St, Anytown, USA",
  },
  {
    id: 5,
    username: "charliebrown",
    token: "wxy345zab678",
    email: "charliebrown@example.com",
    isLogged: true,
    shippingDetails: "222 Pine St, Anytown, USA",
  },
  {
    id: 6,
    username: "johndoe",
    token: "cde456fgh789",
    email: "johndoe@example.com",
    isLogged: false,
    shippingDetails: "333 Cedar St, Anytown, USA",
  },
  {
    id: 7,
    username: "janedoe",
    token: "ijk012lmn345",
    email: "janedoe@example.com",
    isLogged: true,
    shippingDetails: "444 Birch St, Anytown, USA",
  },
  {
    id: 8,
    username: "stevejobs",
    token: "opq678rst901",
    email: "stevejobs@example.com",
    isLogged: false,
    shippingDetails: "555 Oak St, Anytown, USA",
  },
  {
    id: 9,
    username: "billgates",
    token: "uvw234xyz567",
    email: "billgates@example.com",
    isLogged: true,
    shippingDetails: "666 Maple St, Anytown, USA",
  },
  {
    id: 10,
    username: "elonmusk",
    token: "def890abc123",
    email: "elonmusk@example.com",
    isLogged: false,
    shippingDetails: "777 Elm St, Anytown, USA",
  },
];

export default users;
